// The MIT License (MIT)
// © mihakralj
//@version=6
indicator("Volume Weighted Moving Average", "VWMA", overlay=true)

//@function Calculates VWMA using weighted smoothing with compensator
//@doc https://github.com/mihakralj/pinescript/blob/main/indicators/trends_FIR/vwma.md
//@param source Series to calculate VWMA from
//@param period Lookback period - FIR window size
//@returns VWMA value, calculates from first bar using available data
//@optimized for minimum operations and handling dirty data
vwma(series float source, simple int period) =>
    if period <= 0
        runtime.error("Period must be greater than 0")
    int p = math.min(bar_index + 1, period)
    float sum = 0.0
    float actual_weight = 0.0
    int weight_factor = 1
    for i = p - 1 to 0
        if not(na(source[i]) or na(volume[i]))
            sum += source[i] * volume[i] * weight_factor
            actual_weight += volume[i] * weight_factor
        weight_factor += 1
    nz(sum / actual_weight, source)

// ---------- Main loop ----------

// Inputs
i_period = input.int(10, "Period", minval=1)
i_source = input.source(close, "Source")

// Calculation
vwma_value = vwma(i_source, i_period)

// Plot
plot(vwma_value, "Custom VWMA", color.new(color.yellow, 0), 2)
