// The MIT License (MIT)
// © mihakralj
//@version=6
indicator("Weighted Moving Average", "WMA", overlay=true)

//@function Calculates WMA using weighted smoothing with compensator
//@doc https://github.com/mihakralj/pinescript/blob/main/indicators/trends_FIR/wma.md
//@param source Series to calculate WMA from
//@param period Lookback period - FIR window size
//@returns WMA value, calculates from first bar using available data
//@optimized for performance and dirty data
wma(series float source, simple int period) =>
    if period <= 0
        runtime.error("Period must be greater than 0")
    int p = math.min(bar_index + 1, math.min(period, 4000))
    var int last_p = 1
    var float weight_sum = 1.0
    if last_p != p
        weight_sum := p * (p + 1) * 0.5
        last_p := p
    float sum = 0.0
    float actual_weight = 0.0
    for i = 0 to p - 1
        float price = source[i]
        if not na(price)
            float w = p - i
            sum += price * w
            actual_weight += w
    nz(sum / actual_weight, source)


// ---------- Main loop ----------

// Inputs
i_period = input.int(10, "Period", minval=1)
i_source = input.source(close, "Source")

// Calculation
wma_value = wma(i_source, i_period)

// Plot
plot(wma_value, "Custom WMA", color.new(color.yellow, 0), 2)
